/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.InsertController;
import Controller.UpdateController;
import Model.DBConnection;
import Model.DBSearch;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class Doctors extends javax.swing.JFrame {

    /**
     * Creates new form Doctors
     */
    public Doctors() {
        initComponents();
       
        tableLoad();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        doctTF = new javax.swing.JTextField();
        homeTownTF = new javax.swing.JTextField();
        ageTF = new javax.swing.JTextField();
        PhoneTF = new javax.swing.JTextField();
        dspecTF = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        AddBtn = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        updateBtn = new javax.swing.JPanel();
        UpdateBtn = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        DeleteBtn = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        doctorList = new javax.swing.JTable();
        maleRdo = new javax.swing.JRadioButton();
        femaleRdo = new javax.swing.JRadioButton();
        docTF = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        searchDID = new javax.swing.JTextField();
        searchBtn = new javax.swing.JButton();
        clearTf = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(0, 153, 255));

        jLabel3.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Clinic Management system ");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 1339, -1));

        doctTF.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        doctTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doctTFActionPerformed(evt);
            }
        });
        jPanel3.add(doctTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 140, 264, 40));

        homeTownTF.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel3.add(homeTownTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 140, 264, 40));

        ageTF.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ageTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageTFActionPerformed(evt);
            }
        });
        jPanel3.add(ageTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, 180, 40));

        PhoneTF.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel3.add(PhoneTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 230, 270, 40));

        dspecTF.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel3.add(dspecTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 230, 264, 40));

        jPanel6.setBackground(new java.awt.Color(0, 153, 255));

        AddBtn.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        AddBtn.setText("Add Doctors");
        AddBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddBtnMouseClicked(evt);
            }
        });

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Downloads\\addd.png")); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 63, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(AddBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AddBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel3.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(361, 307, -1, 60));

        updateBtn.setBackground(new java.awt.Color(0, 204, 0));
        updateBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateBtnMouseClicked(evt);
            }
        });

        UpdateBtn.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        UpdateBtn.setText("update Doctors");

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Downloads\\6n8fypqp (1).png")); // NOI18N

        javax.swing.GroupLayout updateBtnLayout = new javax.swing.GroupLayout(updateBtn);
        updateBtn.setLayout(updateBtnLayout);
        updateBtnLayout.setHorizontalGroup(
            updateBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, updateBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(UpdateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );
        updateBtnLayout.setVerticalGroup(
            updateBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(updateBtnLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(UpdateBtn)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel3.add(updateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(648, 307, 210, 60));

        jPanel8.setBackground(new java.awt.Color(255, 51, 51));
        jPanel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel8MousePressed(evt);
            }
        });

        DeleteBtn.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        DeleteBtn.setText("Delete Doctors");

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Downloads\\wn0bam05 (1).png")); // NOI18N

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(DeleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(DeleteBtn)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(918, 307, 200, 60));

        jLabel14.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 204, 0));
        jLabel14.setText("Mange Doctors");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 113, -1));

        jLabel15.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 204, 0));
        jLabel15.setText(" Doctors Recorded");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 400, 159, -1));

        doctorList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Doctor Id", "DoctorName ", "Gender", "home town", "age", "Phone", "specialization"
            }
        ));
        doctorList.setGridColor(new java.awt.Color(51, 51, 255));
        doctorList.setRowHeight(25);
        doctorList.setRowSelectionAllowed(false);
        doctorList.setSelectionBackground(new java.awt.Color(0, 255, 0));
        jScrollPane1.setViewportView(doctorList);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 425, 1299, -1));

        buttonGroup1.add(maleRdo);
        maleRdo.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        maleRdo.setText("Male");
        jPanel3.add(maleRdo, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 140, 110, 30));

        buttonGroup1.add(femaleRdo);
        femaleRdo.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        femaleRdo.setText("Female");
        jPanel3.add(femaleRdo, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 140, 130, 30));
        jPanel3.add(docTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, 180, 40));

        jLabel8.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Enter Doctors ID");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, 153, 33));

        searchDID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchDIDActionPerformed(evt);
            }
        });
        jPanel3.add(searchDID, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 50, 180, 30));

        searchBtn.setBackground(new java.awt.Color(102, 255, 102));
        searchBtn.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        searchBtn.setForeground(new java.awt.Color(255, 255, 255));
        searchBtn.setText("Search Doctors");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });
        jPanel3.add(searchBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 50, 150, 33));

        clearTf.setBackground(new java.awt.Color(255, 51, 51));
        clearTf.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        clearTf.setForeground(new java.awt.Color(255, 255, 255));
        clearTf.setText("Clear Fields");
        clearTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearTfActionPerformed(evt);
            }
        });
        jPanel3.add(clearTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 50, -1, 30));

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Downloads\\7777.jpeg")); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 80, 70));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Downloads\\5555 (1).jpeg")); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 110, 110));

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Downloads\\66666 (2).jpeg")); // NOI18N
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 70, 70));

        jLabel19.setBackground(new java.awt.Color(255, 255, 255));
        jLabel19.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Downloads\\trsxg6bv (1).png")); // NOI18N
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 70, 60));

        jLabel23.setBackground(new java.awt.Color(255, 255, 255));
        jLabel23.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Downloads\\333.jpeg")); // NOI18N
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, 70, 80));

        jLabel29.setBackground(new java.awt.Color(255, 255, 255));
        jLabel29.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Downloads\\11111.jpeg")); // NOI18N
        jPanel2.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 710, 80, 80));

        jLabel30.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("Log out");
        jPanel2.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 750, 70, -1));

        jButton5.setBackground(new java.awt.Color(51, 204, 255));
        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Patients");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, -1, -1));

        jButton2.setBackground(new java.awt.Color(51, 204, 255));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Doctors");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, -1, -1));

        jButton3.setBackground(new java.awt.Color(51, 204, 255));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Lab test");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 400, -1, -1));

        jButton4.setBackground(new java.awt.Color(51, 204, 255));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Prescrptions");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 510, -1, -1));

        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 792));

        jLabel2.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jLabel2.setText("Doctors Name");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 120, 120, -1));

        jLabel6.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jLabel6.setText("home town");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 120, 100, -1));

        jLabel7.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jLabel7.setText("Doctors contact number");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 210, 190, -1));

        jLabel10.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jLabel10.setText("age");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, 100, -1));

        jLabel16.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jLabel16.setText("Doctors Speciation");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 210, 150, -1));

        jLabel21.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jLabel21.setText("doctors id");
        jPanel3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, 100, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 1534, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddBtnMouseClicked
tableLoad();
        String dname = doctTF.getText();
        String gender;
        String hTown = homeTownTF.getText();

        String text = ageTF.getText();
        int age = Integer.parseInt(text);

        String text2 = PhoneTF.getText();
        int cNumber = Integer.parseInt(text2);

        String doctSpeci = dspecTF.getText();

        if(maleRdo.isSelected()){

            gender ="Male";

            InsertController.insertDoctors(dname, gender, hTown, age, cNumber, doctSpeci);

            if(femaleRdo.isSelected()){

                gender = "Female";

                InsertController.insertDoctors(dname, gender, hTown, age, cNumber, doctSpeci);
       clearTF();
       tableLoad();
            }}
            // TODO add your handling code here:
    }//GEN-LAST:event_AddBtnMouseClicked

    private void ageTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ageTFActionPerformed

    private void doctTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doctTFActionPerformed
       
        // TODO add your handling code here:
        
    }//GEN-LAST:event_doctTFActionPerformed

    private void clearTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearTfActionPerformed
clearTF(); 


        // TODO add your handling code here:
    }//GEN-LAST:event_clearTfActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        try {
            
            String d_id = searchDID.getText();
            
            ResultSet rs = new DBSearch().searchdoctors(d_id);
            
            while(rs.next()){
            
            String did = rs.getString("d_id");
            String dName = rs.getString("dName");
            String hTown = rs.getString("hTown");
            String gender = rs.getString("speciation");
         
            String age = rs.getString("age");
            String cNumber = rs.getString("cNumber");
            String speciation = rs.getString("speciation");
            
            
              docTF.setText(did);
            doctTF.setText(dName);
            
            if(gender.equals("Male")){
            
            maleRdo.setSelected(true);
            
            }
            if(gender.equals("Female")){
            
            femaleRdo.setSelected(true);
            
            }
            homeTownTF.setText(hTown);
            ageTF.setText(age);
            PhoneTF.setText(cNumber);
            dspecTF.setText(speciation);
            
            
            }
            
          
            
            
            
        } catch (Exception e) {
        }
  
        // TODO add your handling code here:
    }//GEN-LAST:event_searchBtnActionPerformed

    private void searchDIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchDIDActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_searchDIDActionPerformed

      Statement stmt;
    private void updateBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateBtnMouseClicked

if(evt.getSource()== updateBtn){

String dID = docTF.getText();
String dName = doctTF.getText();
String hTown = homeTownTF.getText();
String text =ageTF.getText() ;
int age = Integer.parseInt(text);

String text2 = PhoneTF.getText();
int cNumber = Integer.parseInt(text2);

String Speciation = doctTF.getText();

if(maleRdo.isSelected()){
String dgender = "Male";

UpdateController.updatedoctors(dID,dName, dgender, hTown, age,cNumber , Speciation);

}
if(femaleRdo.isSelected()){
String dgender = "Female";

UpdateController.updatedoctors(dID, dName, dgender, hTown, age,cNumber , Speciation);
}

tableLoad();
}


        // TODO add your handling code here:
    }//GEN-LAST:event_updateBtnMouseClicked

    private void jPanel8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel8MousePressed


String dID = docTF.getText();

        try {
            
            stmt = DBConnection.getStatementConnection();
            stmt.executeUpdate("DELETE FROM doctors WHERE d_id= '"+dID+"' ");
            
            if(dID.equals("")){
                
                 
            }
            else{
                 JOptionPane.showMessageDialog(null, "Record Deleted successfully");
                
            }
            
          
            
        } catch (Exception e) {
        }
        
        tableLoad();
clearTF();
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel8MousePressed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        Patients p = new Patients();
        p.setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Doctors d = new Doctors();
        d.setVisible(true);
        this.dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        testLab t= new testLab();
        t.setVisible(true);
        this.dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        Prescriptions p = new Prescriptions();
        p.setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed
public void tableLoad(){
    
    ResultSet rs = new DBSearch().searchAlldoctors();
    
        try {
            DefaultTableModel tb1Model = ( DefaultTableModel)doctorList.getModel();
            tb1Model.setRowCount(0);
            
            while(rs.next()){
            String did =rs.getString("d_id");
                   
            String dname =rs.getString("dName");
            String dgender = rs.getString("dgender");
            String hTown =rs.getString("hTown");
            String age = rs.getString("age");
            String cNumber =rs.getString("cNumber");
            String speciation =rs.getString("speciation");
            
            String tbData[] = {did,dname,dgender,hTown,age,cNumber,speciation};
           
            
            tb1Model.addRow(tbData);
            
            }
        } catch (Exception e) {
            
        }
   
}
     
     
       public void clearTF(){
    
    doctTF.setText("");
    homeTownTF.setText("");
    ageTF.setText("");
    PhoneTF.setText("");
    dspecTF.setText("");
    maleRdo.setSelected(false);
    femaleRdo.setSelected(false);
    docTF.setText("");
    searchDID.setText("");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Doctors.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Doctors.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Doctors.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Doctors.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Doctors().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddBtn;
    private javax.swing.JLabel DeleteBtn;
    private javax.swing.JTextField PhoneTF;
    private javax.swing.JLabel UpdateBtn;
    private javax.swing.JTextField ageTF;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton clearTf;
    private javax.swing.JTextField docTF;
    private javax.swing.JTextField doctTF;
    private javax.swing.JTable doctorList;
    private javax.swing.JTextField dspecTF;
    private javax.swing.JRadioButton femaleRdo;
    private javax.swing.JTextField homeTownTF;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton maleRdo;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTextField searchDID;
    private javax.swing.JPanel updateBtn;
    // End of variables declaration//GEN-END:variables
}
