/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.InsertController;
import Model.DBSearch;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
import Controller.UpdateController;
import Model.DBConnection;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class Patients extends javax.swing.JFrame {
    
    
    

    /**
     * Creates new form Patients
     */
    public Patients() {
        initComponents();
        tableLoad();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gender = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        PatNameTF = new javax.swing.JTextField();
        homeTownTF = new javax.swing.JTextField();
        ageTF = new javax.swing.JTextField();
        PhoneTF = new javax.swing.JTextField();
        allergiesTF = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        AddBtn = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        updateBtn = new javax.swing.JPanel();
        UpdateBtn = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        deleteBtn = new javax.swing.JPanel();
        DeleteBtn = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        PatientsList = new javax.swing.JTable();
        femaleRdo = new javax.swing.JRadioButton();
        maleRdo = new javax.swing.JRadioButton();
        clear = new javax.swing.JButton();
        searchPID = new javax.swing.JTextField();
        searchBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        pIDTF = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Downloads\\7777.jpeg")); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 80, 70));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Downloads\\5555 (1).jpeg")); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 110, 110));

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Downloads\\66666 (2).jpeg")); // NOI18N
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 70, 70));

        jLabel19.setBackground(new java.awt.Color(255, 255, 255));
        jLabel19.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Downloads\\trsxg6bv (1).png")); // NOI18N
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 70, 60));

        jLabel23.setBackground(new java.awt.Color(255, 255, 255));
        jLabel23.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Downloads\\333.jpeg")); // NOI18N
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, 70, 80));

        jLabel29.setBackground(new java.awt.Color(255, 255, 255));
        jLabel29.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Downloads\\11111.jpeg")); // NOI18N
        jPanel2.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 690, 80, 80));

        jLabel30.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("Log out");
        jPanel2.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 730, 70, -1));

        jButton1.setBackground(new java.awt.Color(51, 204, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Doctors");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, -1, -1));

        jButton2.setBackground(new java.awt.Color(51, 204, 255));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Lab test");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 400, -1, -1));

        jButton3.setBackground(new java.awt.Color(51, 204, 255));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Prescrptions");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 510, -1, -1));

        jButton4.setBackground(new java.awt.Color(51, 204, 255));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Patients");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 792));

        jPanel3.setBackground(new java.awt.Color(0, 153, 255));

        jLabel2.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Clinic Management system ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 1320, -1));

        PatNameTF.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        PatNameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PatNameTFActionPerformed(evt);
            }
        });
        jPanel1.add(PatNameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 110, 264, 40));

        homeTownTF.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel1.add(homeTownTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 110, 264, 40));

        ageTF.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ageTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageTFActionPerformed(evt);
            }
        });
        jPanel1.add(ageTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 200, 270, 40));

        PhoneTF.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel1.add(PhoneTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 200, 264, 40));

        allergiesTF.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel1.add(allergiesTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 200, 264, 40));

        jPanel4.setBackground(new java.awt.Color(0, 204, 255));

        AddBtn.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        AddBtn.setText("Add Patients");
        AddBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddBtnMouseClicked(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Downloads\\addd.png")); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AddBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(7, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(AddBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, -1, 60));

        updateBtn.setBackground(new java.awt.Color(0, 204, 51));
        updateBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                updateBtnMousePressed(evt);
            }
        });

        UpdateBtn.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        UpdateBtn.setText("update Patient");

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Downloads\\6n8fypqp (1).png")); // NOI18N

        javax.swing.GroupLayout updateBtnLayout = new javax.swing.GroupLayout(updateBtn);
        updateBtn.setLayout(updateBtnLayout);
        updateBtnLayout.setHorizontalGroup(
            updateBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, updateBtnLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(UpdateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        updateBtnLayout.setVerticalGroup(
            updateBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, updateBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(updateBtnLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(UpdateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel1.add(updateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 260, -1, 60));

        deleteBtn.setBackground(new java.awt.Color(255, 51, 51));
        deleteBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                deleteBtnMousePressed(evt);
            }
        });

        DeleteBtn.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        DeleteBtn.setText("Delete Patients");

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Downloads\\wn0bam05 (1).png")); // NOI18N

        javax.swing.GroupLayout deleteBtnLayout = new javax.swing.GroupLayout(deleteBtn);
        deleteBtn.setLayout(deleteBtnLayout);
        deleteBtnLayout.setHorizontalGroup(
            deleteBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, deleteBtnLayout.createSequentialGroup()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(DeleteBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                .addContainerGap())
        );
        deleteBtnLayout.setVerticalGroup(
            deleteBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(deleteBtnLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(DeleteBtn)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel1.add(deleteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 260, -1, 60));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 204, 0));
        jLabel11.setText("Mange Patient");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 158, 26));

        jLabel12.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 204, 51));
        jLabel12.setText(" Patient Recorded");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 340, 159, -1));

        PatientsList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Patient Id", "Patient Name ", "Gemder", "Home Town", "age ", "contact number", "Allergies"
            }
        ));
        PatientsList.setGridColor(new java.awt.Color(51, 51, 255));
        PatientsList.setRowHeight(25);
        PatientsList.setRowSelectionAllowed(false);
        PatientsList.setSelectionBackground(new java.awt.Color(0, 255, 0));
        jScrollPane1.setViewportView(PatientsList);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 365, 1290, -1));

        gender.add(femaleRdo);
        femaleRdo.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        femaleRdo.setText("Female");
        jPanel1.add(femaleRdo, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 103, 100, 50));

        gender.add(maleRdo);
        maleRdo.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        maleRdo.setText("Male");
        jPanel1.add(maleRdo, new org.netbeans.lib.awtextra.AbsoluteConstraints(808, 104, 90, 50));

        clear.setBackground(new java.awt.Color(255, 0, 0));
        clear.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        clear.setForeground(new java.awt.Color(255, 255, 255));
        clear.setText("Clear Fields");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        jPanel1.add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 40, 120, 30));

        searchPID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchPIDActionPerformed(evt);
            }
        });
        jPanel1.add(searchPID, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 40, 218, 30));

        searchBtn.setBackground(new java.awt.Color(102, 255, 102));
        searchBtn.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        searchBtn.setForeground(new java.awt.Color(255, 255, 255));
        searchBtn.setText("Search patient");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });
        jPanel1.add(searchBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 40, 140, 33));

        jLabel3.setBackground(new java.awt.Color(204, 204, 255));
        jLabel3.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Enter Patient ID");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 40, 153, 33));

        pIDTF.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        pIDTF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pIDTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pIDTFActionPerformed(evt);
            }
        });
        jPanel1.add(pIDTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, 170, 40));

        jLabel7.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jLabel7.setText("Patients Name");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 90, 110, 20));

        jLabel9.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jLabel9.setText("Home Town");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 90, 100, 20));

        jLabel13.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jLabel13.setText("Patients age");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 180, 110, 20));

        jLabel14.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jLabel14.setText("Patients contact number");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 180, 190, 20));

        jLabel15.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jLabel15.setText("allergies");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 180, 100, 20));

        jLabel16.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jLabel16.setText("Patient ID");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, 80, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ageTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ageTFActionPerformed

    private void AddBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddBtnMouseClicked

        String pid =pIDTF.getText();
        String pname = PatNameTF.getText();
        String gender;
        String hTown = homeTownTF.getText();
        
        String text = ageTF.getText();
        int age = Integer.parseInt(text);
        
        String text2 = PhoneTF.getText();
        int cNumber = Integer.parseInt(text2);
        
        String allergies = allergiesTF.getText();
        
        
        if(maleRdo.isSelected()){
        
        gender ="Male";
        
        InsertController.insertPatient( pname, gender, hTown, age, cNumber, allergies);
        }
        
       if(femaleRdo.isSelected()){
       
       gender = "Female";
       
        InsertController.insertPatient( pname, gender, hTown, age, cNumber, allergies);
       }
        
       clearTF();
       tableLoad();
    }//GEN-LAST:event_AddBtnMouseClicked

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed

 clearTF();

        // TODO add your handling code here:
    }//GEN-LAST:event_clearActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed


        try {
            
            String p_id = searchPID.getText();
            
            ResultSet rs = new DBSearch().searchPatient(p_id);
            
            while(rs.next()){
            
            String pid = rs.getString("p_id");
            String pName = rs.getString("pName");
            String hTown = rs.getString("hTown");
            String gender = rs.getString("gender");
         
            String age = rs.getString("age");
            String cNumber = rs.getString("cNumber");
            String allergies = rs.getString("allergies");
            
            
              pIDTF.setText(pid);
            PatNameTF.setText(pName);
            
            if(gender.equals("Male")){
            
            maleRdo.setSelected(true);
            
            }
            if(gender.equals("Female")){
            
            femaleRdo.setSelected(true);
            }
            homeTownTF.setText(hTown);
            ageTF.setText(age);
            PhoneTF.setText(cNumber);
            allergiesTF.setText(allergies);
            
            
            }
            
          
            
            
            
        } catch (Exception e) {
        }


        // TODO add your handling code here:
    }//GEN-LAST:event_searchBtnActionPerformed

    private void PatNameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PatNameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PatNameTFActionPerformed

    private void updateBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateBtnMousePressed

        
        

if(evt.getSource()== updateBtn){

String pID = pIDTF.getText();
String pName = PatNameTF.getText();
String hTown = homeTownTF.getText();
String text =ageTF.getText() ;
int age = Integer.parseInt(text);

String text2 = PhoneTF.getText();
int cNumber = Integer.parseInt(text2);

String allergies = allergiesTF.getText();

if(maleRdo.isSelected()){
String gender = "Male";

UpdateController.updatepatient(pID, pName, gender, hTown, age,cNumber , allergies);

}
if(femaleRdo.isSelected()){
String gender = "Female";

UpdateController.updatepatient(pID, pName, gender, hTown, age,cNumber , allergies);
}

tableLoad();
clearTF();
}



        // TODO add your handling code here:
    }//GEN-LAST:event_updateBtnMousePressed

    private void pIDTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pIDTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pIDTFActionPerformed

    private void searchPIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchPIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchPIDActionPerformed

    Statement stmt;
    
    private void deleteBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteBtnMousePressed



String pID = pIDTF.getText();

        try {
            
            stmt = DBConnection.getStatementConnection();
            stmt.executeUpdate("DELETE FROM patient WHERE p_id= '"+pID+"' ");
            
            if(pID.equals("")){
                
                 
            }
            else{
                 JOptionPane.showMessageDialog(null, "Record Deleted successfully");
                
            }
            
          
            
        } catch (Exception e) {
        }

tableLoad();
clearTF();
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteBtnMousePressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
Doctors d = new Doctors();
d.setVisible(true);
this.dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

testLab d= new testLab();
d.setVisible(true);
this.dispose();

// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

Prescriptions p = new Prescriptions();
p.setVisible(true);
this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    
    public void clearTF(){
    
    PatNameTF.setText("");
    homeTownTF.setText("");
    ageTF.setText("");
    PhoneTF.setText("");
    allergiesTF.setText("");
    maleRdo.setSelected(false);
    femaleRdo.setSelected(false);
    pIDTF.setText("");
    searchPID.setText("");
    }
    
    
    public void tableLoad(){
    
    ResultSet rs = new DBSearch().searchAllPatient();
    
        try {
            DefaultTableModel tb1Model = ( DefaultTableModel)PatientsList.getModel();
            tb1Model.setRowCount(0);
            
            while(rs.next()){
            String pid =rs.getString("p_id");
                   
            String pname =rs.getString("pName");
            String gender = rs.getString("gender");
            String hTown =rs.getString("hTown");
            String age = rs.getString("age");
            String cNumber =rs.getString("cNumber");
            String allergies =rs.getString("allergies");
            
            String tbData[] = {pid,pname,gender,hTown,age,cNumber,allergies};
           
            
            tb1Model.addRow(tbData);
            
            }
        } catch (Exception e) {
        }
    
    
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Patients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Patients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Patients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Patients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Patients().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddBtn;
    private javax.swing.JLabel DeleteBtn;
    private javax.swing.JTextField PatNameTF;
    private javax.swing.JTable PatientsList;
    private javax.swing.JTextField PhoneTF;
    private javax.swing.JLabel UpdateBtn;
    private javax.swing.JTextField ageTF;
    private javax.swing.JTextField allergiesTF;
    private javax.swing.JButton clear;
    private javax.swing.JPanel deleteBtn;
    private javax.swing.JRadioButton femaleRdo;
    private javax.swing.ButtonGroup gender;
    private javax.swing.JTextField homeTownTF;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton maleRdo;
    private javax.swing.JTextField pIDTF;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTextField searchPID;
    private javax.swing.JPanel updateBtn;
    // End of variables declaration//GEN-END:variables
}
